### PR TITLE
Modify readme to include Docusaurus start steps

### PR DESCRIPTION
**Pull request by Buddhika-Pathirathna**

### CODE REVIEW

**Review by GloreenS — APPROVED** [review]
Looks good! Thanks!

**Review by ipopescu — COMMENTED** [review]
@Buddhika-Pathirathna While reviewing, I decided to take the opportunity to move the section you added higher in the document and to re-write the rest of the file for more clarity (since my attention was on this file).
I removed outdated sections such as the Github flow for subtree commands. I removed duplicated setup instructions, and I updated the explanations for easier reading.
@GloreenS @Buddhika-Pathirathna — Please take a look at the changes. 
Gloreen, if you approve them, then you or Buddhika can merge without waiting for my review since I contributed in this case. Thank you!

**Comment by Buddhika-Pathirathna** [comment]
> @Buddhika-Pathirathna While reviewing, I decided to take the opportunity to move the section you added higher in the document and to re-write the rest of the file for more clarity (since my attention was on this file). I removed outdated sections such as the Github flow for subtree commands. I removed duplicated setup instructions, and I updated the explanations for easier reading. @GloreenS @Buddhika-Pathirathna — Please take a look at the changes. Gloreen, if you approve them, then you or Buddhika can merge without waiting for my review since I contributed in this case. Thank you!

Thanks, @ipopescu for taking time to review, will check the changes provide any update if there is.

**Review by GloreenS — APPROVED** [review]
Looks good!

**Pull request merged**
